#!/usr/bin/env bash
# =============================================================================
#  setup-wallpaper.sh  (KDE / Kinoite edition)
# -----------------------------------------------------------------------------
#  Ships + applies the Anubis OS wallpaper set to KDE Plasma 6:
#
#    * Wallpapers (7 files) shipped flat under /usr/share/wallpapers/anubis-os/
#      by the `files` module. Plasma's wallpaper picker discovers them
#      automatically (no XML manifest needed — that's a GNOME thing).
#    * Default wallpaper for new users → /etc/skel/.config/
#      plasma-org.kde.plasma.desktop-appletsrc with Image= pre-set.
#    * Lockscreen wallpaper → /etc/skel/.config/kscreenlockerrc
#    * SDDM background → /etc/sddm.conf.d/anubis-background.conf
#    * Purges stock Fedora / KDE wallpapers to free ~50–150 MB and de-clutter
#      the wallpaper picker.
#
#  Prereqs:
#    * files/usr/share/wallpapers/anubis-os/* (7 wallpapers shipped by `files`)
#    * files/usr/share/pixmaps/anubis-logo.png (shipped by `files`)
#
#  Idempotent. Runs at BUILD TIME.
# =============================================================================
set -euo pipefail
trap 'echo "[setup-wallpaper] FAILED at line $LINENO" >&2' ERR

LOG() { printf '[setup-wallpaper] %s\n' "$*"; }

WALLPAPER_DIR=/usr/share/wallpapers/anubis-os
DEFAULT_WALLPAPER="$WALLPAPER_DIR/anubis-wallpaper.png"

# --- 0. Verify shipped files ------------------------------------------------
if [[ ! -d "$WALLPAPER_DIR" ]]; then
    echo "[setup-wallpaper] ERROR: $WALLPAPER_DIR not found — did the files module run first?" >&2
    exit 1
fi
if [[ ! -f "$DEFAULT_WALLPAPER" ]]; then
    echo "[setup-wallpaper] ERROR: default wallpaper $DEFAULT_WALLPAPER not found." >&2
    exit 1
fi

WALLPAPER_COUNT=$(find "$WALLPAPER_DIR" -maxdepth 1 -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | wc -l)
LOG "$WALLPAPER_COUNT wallpaper(s) present in $WALLPAPER_DIR"

# --- 1. Purge stock KDE / Fedora wallpapers --------------------------------
LOG "Purging stock KDE + Fedora wallpapers ..."
# KDE stock wallpapers (Shallow, Sea, etc.)
rm -rf /usr/share/wallpapers/Next              2>/dev/null || true
rm -rf /usr/share/wallpapers/Onze              2>/dev/null || true
# Fedora versioned wallpaper dirs (f40, f41, f44, ...)
find /usr/share/backgrounds -maxdepth 1 -type d -name 'f[0-9]*' \
    -exec rm -rf {} + 2>/dev/null || true
rm -rf /usr/share/backgrounds/gnome 2>/dev/null || true
# Old GNOME background-properties XML files (if any survived the kinoite base)
find /usr/share/gnome-background-properties -maxdepth 1 -type f \
    -exec rm -f {} + 2>/dev/null || true

# --- 2. Default desktop wallpaper (per-user, via /etc/skel) ----------------
# Plasma 6's desktop wallpaper config lives in
# ~/.config/plasma-org.kde.plasma.desktop-appletsrc
# We ship a minimal version that sets the wallpaper on first login. Plasma
# will read this on first launch and pick up the Anubis wallpaper.
LOG "Writing /etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc ..."
mkdir -p /etc/skel/.config
cat > /etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc <<APPSRC
# Anubis OS — default Plasma 6 desktop wallpaper config.
# Generated by setup-wallpaper.sh. Plasma will read this on first login.
# After first launch, the user can change the wallpaper normally via
# System Settings > Wallpaper.

[ActionPlugins][0]
MiddleButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextMenu

[Containments][1]
activity=00000000-0000-0000-0000-000000000000
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.plasma.folder
wallpaperplugin=org.kde.image

[Containments][1][Wallpaper][org.kde.image][General]
Image=file://$DEFAULT_WALLPAPER
FillMode=6
SlidePaths=$WALLPAPER_DIR

[Containments][2]
activity=00000000-0000-0000-0000-000000000000
formfactor=2
immutability=1
lastScreen=0
location=3
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][2][Applets][1]
immutability=1
plugin=org.kde.plasma.kickoff

[Containments][2][Applets][1][Configuration]
icon=anubis-logo

[Containments][2][Applets][2]
immutability=1
plugin=org.kde.plasma.icontasks

[Containments][2][Applets][3]
immutability=1
plugin=org.kde.plasma.systemtray

[Containments][2][Applets][4]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][2][General]
AppletOrder=1,2,3,4
APPSRC

# --- 3. Lockscreen wallpaper (per-user) ------------------------------------
LOG "Writing /etc/skel/.config/kscreenlockerrc ..."
cat > /etc/skel/.config/kscreenlockerrc <<KSL
[Greeter]
Wallpaper=file://$DEFAULT_WALLPAPER
WallpaperPlugin=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
Image=file://$DEFAULT_WALLPAPER
FillMode=6
KSL

# --- 4. SDDM background -----------------------------------------------------
# SDDM breeze theme uses the Plasma wallpaper as its background by default.
# We override it explicitly so the login screen always shows the Anubis
# wallpaper even if the user later changes their desktop wallpaper.
LOG "Writing /etc/sddm.conf.d/anubis-background.conf ..."
mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/anubis-background.conf <<SDDM
[Theme]
Current=breeze
ThemeDir=/usr/share/sddm/themes

# Breeze theme reads its background from this path; we ship a copy of the
# default Anubis wallpaper into the breeze theme dir in setup-logo.sh.
# Force a specific background override:
SDDM

# Also drop the default wallpaper into the breeze theme dir as background.png
# (this is what breeze theme uses if no theme.conf override is present).
BREEZE_DIR=/usr/share/sddm/themes/breeze
if [[ -d "$BREEZE_DIR" ]]; then
    install -Dm644 "$DEFAULT_WALLPAPER" "$BREEZE_DIR/background.png"
    # Patch theme.conf to use background.png explicitly.
    if [[ -f "$BREEZE_DIR/theme.conf" ]]; then
        if grep -q '^[# ]*background=' "$BREEZE_DIR/theme.conf"; then
            sed -i "s|^[# ]*background=.*|background=background.png|" "$BREEZE_DIR/theme.conf"
        else
            echo 'background=background.png' >> "$BREEZE_DIR/theme.conf"
        fi
    fi
fi

# --- 5. KDE globals — dark theme + color scheme ----------------------------
# /etc/skel/.config/kdeglobals is Plasma's master config. Set dark mode + the
# Anubis color scheme so first login is already themed.
LOG "Writing /etc/skel/.config/kdeglobals ..."
cat > /etc/skel/.config/kdeglobals <<'KDEGLOBALS'
[Colors:View]
BackgroundNormal=#1a0a2e
ForegroundNormal=#e5e7eb

[General]
ColorScheme=AnubisPurple
Name=Anubis OS

[KDE]
LookAndFeelPackage=org.kde.breezedark.desktop
widgetStyle=Breeze

[Icons]
Theme=breeze-dark
KDEGLOBALS

# --- 6. Apply SDDM theme cache refresh -------------------------------------
# (no-op at build time; SDDM will pick up the theme on next start)

LOG "Done. Wallpapers + Plasma defaults installed."
