name: Build anubis-os images

on:
  push:
    branches:
      - main
    paths:
      - "recipes/**"
      - "files/**"
      - "modules/**"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 6 * * 1" # Roda automaticamente toda segunda-feira às 06:00 UTC
  workflow_dispatch: # Permite que você clique em "Run workflow" manualmente no GitHub

jobs:
  build:
    name: Build (anubis-os)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: blue-build/github-action@v1
        with:
          recipe: recipe.yml
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          pr_event_number: ${{ github.event.number }}
          cosign_private_key: ${{ secrets.COSIGN_PRIVATE_KEY }}
