name: Build anubis-os images
on:
  push:
    branches: [main]
    paths:
      - "recipes/**"
      - "files/**"
      - "modules/**"
      - ".github/workflows/build.yml"
  schedule:
    cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  build:
    name: Build (anubis-os)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # CRUCIAL: Permite que o Cosign valide a identidade do GitHub sem chave privada fixa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: blue-build/github-action@v1
        with:
          recipe: recipe.yml
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          pr_event_number: ${{ github.event.number }}
          # REMOVIDO: build_opts: "--no-sign" (Agora ele vai assinar por padrão)
          # REMOVIDO: cosign_private_key: "" (Deixando vazio ou oculto força o modo Keyless via Sigstore)
